// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB96shQ3dtfWgTTLNlZ44BVTzUNs_vDTWU',
    appId: '1:559254163826:web:f8ecffa5e5972d98ac4deb',
    messagingSenderId: '559254163826',
    projectId: 'laza-4c8d7',
    authDomain: 'laza-4c8d7.firebaseapp.com',
    storageBucket: 'laza-4c8d7.appspot.com',
    measurementId: 'G-66X2YXGXK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ypfzR9-dUuefudgCwxEJDdmq8eEjXe4',
    appId: '1:559254163826:android:ae6b9712a02795caac4deb',
    messagingSenderId: '559254163826',
    projectId: 'laza-4c8d7',
    storageBucket: 'laza-4c8d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW2Q4lfac2MXJlFJ1VOmCnQFlgPXdMsgA',
    appId: '1:559254163826:ios:96f2702bc4d7635fac4deb',
    messagingSenderId: '559254163826',
    projectId: 'laza-4c8d7',
    storageBucket: 'laza-4c8d7.appspot.com',
    iosClientId: '559254163826-b3g9v4a26u02392kc1irbfg4omv5oqji.apps.googleusercontent.com',
    iosBundleId: 'com.example.laza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW2Q4lfac2MXJlFJ1VOmCnQFlgPXdMsgA',
    appId: '1:559254163826:ios:bedfd4667d98294cac4deb',
    messagingSenderId: '559254163826',
    projectId: 'laza-4c8d7',
    storageBucket: 'laza-4c8d7.appspot.com',
    iosClientId: '559254163826-magl1hdj3jkjq0hgrggj908p51uor422.apps.googleusercontent.com',
    iosBundleId: 'com.example.laza.RunnerTests',
  );
}
